apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  destination:
    namespace: adi
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - adi-services.yaml
      parameters:
      - name: services.kafka.envVars.queue_address
        value: $dns_name
      - name: services.ui.ingress[0].host
        value: $dns_name           
    path: centerity-charts/simple-service-template/
    repoURL: https://gitlab.com/adi/global-deployment.git
    targetRevision: centos
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true 
